#ifndef CONFIGURATION_POLLUTION_PAR_H
#define  CONFIGURATION_POLLUTION_PAR_H 12345

#define HOW_OFTEN_POLLUTION 30
#define CO2_THRESHOLD 123 //NOT REALISTIC VALUE
#define CO_THRESHOLD 222 //NOT REALISTIC VALUE

#endif
