#ifndef CONFIGURATION_PARAMETER_H
#define CONFIGURATION_PARAMETER_H 12345

#define HOW_OFTEN 4
#define HOW_OFTEN_POLLUTION 30
#define CO2_THRESHOLD 123 //NOT REALISTIC VALUE
#define CO_THRESHOLD 222 //NOT REALISTIC VALUE

#endif
